packaging_format = 2

id = "umap"
name = "umap"
description.fr = "Logiciel libre de cartographie"

version = "0.0.25"

maintainers = ["frju365, cyp"]

[upstream]
license = "AGPLv3"
website = "https://umap.openstreetmap.fr/"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">> 2.3.15"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = false
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.path_url]
    ask.en = "Choose a path for umap"
    ask.fr = "Choisissez un chemin pour umap"
    type = "path"
    example = "/umap"
    default = "/umap"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    choices = ["en_EN", "fr_FR"]
    default = "fr_FR"

    [install.init_main_permission]
    type = "group"
    default = "true"

    [install.github_key]
    ask.en = "GitHub Key (Optional field)"
    ask.fr = "Clé GitHub (Champs optionnel)"
    optional = true

    [install.github_secret]
    ask.en = "GitHub Secret Key (Optional field)"
    ask.fr = "Clé secret GitHub (Champs optionnel)"
    optional = true

    [install.github_scope]
    ask.en = "GitHub Scope (Optional field)"
    ask.fr = "GitHub Scope (Champs optionnel)"
    optional = true
    example = "[\"user:email\", ]"

    [install.bitbucket_key]
    ask.en = "Bitbucket Key (Optional field)"
    ask.fr = "Clé Bitbucket (Champs optionnel)"
    optional = true

    [install.bitbucket_secret]
    ask.en = "Bitbucket Secret Key (Optional field)"
    ask.fr = "Clé secret Bitbucket (Champs optionnel)"
    optional = true

    [install.twitter_key]
    ask.en = "Twitter Key (Optional field)"
    ask.fr = "Clé Twitter (Champs optionnel)"
    optional = true

    [install.twitter_secret]
    ask.en = "Twitter Secret Key (Optional field)"
    ask.fr = "Clé secret Twitter (Champs optionnel)"
    optional = true

    [install.openstreetmap_key]
    ask.en = "Openstreetmap Key (Optional field)"
    ask.fr = "Clé Openstreetmap (Champs optionnel)"
    optional = true

    [install.openstreetmap_secret]
    ask.en = "Openstreetmap Secret Key (Optional field)"
    ask.fr = "Clé secret Openstreetmap (Champs optionnel)"
    optional = true

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.database]
    type = "postgresql"
