#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

if [ ! -e .fonctions ]; then
	# Get file fonction if not been to the current directory
	sudo cp ../settings/scripts/.fonctions ./.fonctions
	sudo chmod a+rx .fonctions
fi
# Loads the generic functions usually used in the script
source .fonctions
# Source app helpers
source /usr/share/yunohost/helpers

# Get multi-instances specific variables
#REMOVEME? app=$YNH_APP_INSTANCE_NAME

# Retrieve app settings
#REMOVEME? domain=$(ynh_app_setting_get "$app" domain)

# Copy the app files
#REMOVEME? install_dir="/opt/${app}"
ynh_backup "$install_dir" "sources" 1

# Copy the nginx conf files
ynh_backup "/etc/nginx/conf.d/${domain}.d/${app}.conf" "nginx.conf"

# Backup db
ynh_psql_dump_db $app > /var/lib/postgresql/${app}_db.sql
ynh_backup "/var/lib/postgresql/${app}_db.sql" "${app}_db.sql"
ynh_secure_remove "/var/lib/postgresql/${app}_db.sql"
